version: "3.7"

services:

  kcat1:
    image: edenhill/kcat:1.7.1
    entrypoint: ""
    command: /bin/sh -c 'kcat -P -b kafka:19092 -X message.max.bytes=100000000  -t test-fhir-patient /data/* '
    volumes:
      - ${DATA_DIR:-./test-data}:/data:ro

  kcat2:
    image: edenhill/kcat:1.7.1
    entrypoint: ""
    command: /bin/sh -c 'kcat -P -b kafka:19092 -X message.max.bytes=100000000  -t test-fhir-lufu /data/*'
    volumes:
      - ${DATA_DIR:-./test-data}:/data:ro

  kcat3:
    image: edenhill/kcat:1.7.1
    entrypoint: ""
    command: /bin/sh -c 'kcat -P -b kafka:19092 -X message.max.bytes=100000000 -t test-fhir-lab /data/*'
    volumes:
      - ${DATA_DIR:-./test-data}:/data:ro

