spring:
  jmx:
    enabled: true
  kafka:
    bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9092}
    security.protocol: ${SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      trust-store-location: file://${SSL_TRUST_STORE_LOCATION_INTERNAL:/opt/kafka-pseudonymiser/ssl/truststore.jks}
      trust-store-password: ${SSL_TRUST_STORE_PASSWORD}
      key-store-location: file://${SSL_KEY_STORE_LOCATION_INTERNAL:/opt/kafka-pseudonymiser/ssl/keystore.jks}
      key-store-password: ${SSL_KEY_STORE_PASSWORD}
    producer:
      compression-type: gzip
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.miracum.kafka.serializers.KafkaFhirSerializer

  cloud:
    stream:
      bindings:
        process-in-0:
          destination: ${INPUT_TOPIC:fhir-patient,fhir-lab,fhir-lufu,lufu-fhir}
          group: pseudonymizer
          consumer:
            useNativeDecoding: true
        process-out-0:
          producer:
            useNativeEncoding: true
      kafka:
        bindings:
          process-in-0:
            consumer:
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: org.miracum.kafka.serializers.KafkaFhirDeserializer
          process-out-0:
            producer:
              configuration:
                compression.type: ${COMPRESSION_TYPE:gzip}


services:
  pseudonymizer:
    url: "http://localhost:5000/fhir"

  kafka:
    generate-output-topic:
      match-expression: "fhir\\-"
      replace-with: "psn-fhir-"


server:
  port: 8089

#management:
#  server:
#    port: 8089
#  endpoints:
#    web:
#      exposure:
#        include: "health, prometheus, info, metric"
#  endpoint:
#    health:
#      show-details: always

logging:
  level:
    org.springframework.kafka.config: info
    de.unimarburg.diz.kafkastreamPseudonymiser: debug
