version: "3.7"

services:
  kafka-pseudonymizer:
    image: registry.diz.uni-marburg.de/etl/kafka-pseudonymizer:${IMAGE_TAG:?}
    environment:
      SPRING_CLOUD_STREAM_BINDINGS_PROCESS_IN_0_DESTINATION: ${INPUT_TOPICS:?}
      SERVICES_KAFKA_GENERATE_OUTPUT_TOPIC_MATCH_EXPRESSION: ${MATCH_EXP:?}
      SERVICES_KAFKA_GENERATE_OUTPUT_TOPIC_REPLACE_WITH: ${REPLACE_EXP:?}
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: ${KAFKA_BROKERS:?}
      SERVICES_PSEUDONYMIZER_URL: ${PSEUDONYMIZER_URL}
      SECURITY_PROTOCOL: SSL
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD:?}
      SSL_TRUST_STORE_PASSWORD: ${SSL_TRUST_STORE_PASSWORD:?}
    ports:
      - "${PSN_WEB_PORT}:8080"
    volumes:
      - ${SSL_KEY_STORE_LOCATION}:/opt/kafka-pseudonymizer/ssl/keystore.jks
      - ${SSL_TRUST_STORE_LOCATION}:/opt/kafka-pseudonymizer/ssl/truststore.jks
